[package]
name = "ruststuff"
version = "0.1.0"
edition = "2021"

[dependencies]
core_simd = { git = "https://github.com/rust-lang/portable-simd" }
clap = { version = "3.0", features = ["derive"] }

[[bin]]
name = "simd"
path = "src/simd/main.rs"

[[bin]]
name = "cli"
path = "src/cli/main.rs"